name: zip2
description: A small zip library totally based on stream and transformer.
version: 1.0.1
repository: https://github.com/lindeer/zip2

topics:
  - zip
  - stream

environment:
  sdk: ^3.0.0

executables:
  dzip: zip
  undzip: unzip

dependencies:
  path: ^1.9.1
  glob: ^2.1.3

dev_dependencies:
  lints: ^5.0.0
  test: ^1.26.2
