name: zip2
description: A small zip library totally based on stream and transformer.
version: 1.0.0
repository: https://github.com/lindeer/zip2

environment:
  sdk: ^3.0.0

dependencies:
  path: ^1.9.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.26.2
